# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51916b270c2383c11bdd716aea7d05efee83c722345ba4101c661c3316a741465ad50557194fe9461adf79ff48c60cfa139aa049d5606539d93925c7653fa716

test:
  secret_key_base: 5aeca8cd2ec34c45c2db1cb583e32dea2c8c5709a1a4a1932cfb6fec637f45755a0a7d6b16cb207b1ab4ee2d4a2a7306be5b4012c16798e9ef16972ddd451b51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
